################################# Default configuration ###################
# provide your domain here
baseURL = "https://terrasaas.netlify.app/"
# theme
theme = "dot"
# site title
title = "TerraSaas - Cloud Architecture"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
# logo = "images/logo.png"
# logo white is for homepage logo, you can use colorful logo too...
# logo_white = "images/logo-text.png"
# when logo is empty, it will shown your site title

# customize color
primary_color = "#6930c3" #"#02007e"
body_color = "#f9f9f9"
white_color = "#ffffff"
light_color = "#e5e5e5"
text_color = "#14213d"
text_color_dark = "#000000"

# font family
font_family = "Lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
text = "Contact"
link = "/contact"

[[params.social]]
text = "FAQ"
link = "/faq"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://www.github.com/butterops"
target = "blank"

[[params.social]]
icon = "ti-slack" # themify icon pack : https://themify.me/themify-icons
link = "https://butterops.slack.com"
target = "blank"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "©2021- A modern infrastructure and cloud migration guide maintained and updated by [ButterOps](https://butterops.dev/)"

# banner
[Languages.en.params.banner]
title = "Migrate Your SaaS Apps & APIs Into The Cloud"
subtitle = "Fully Automated <b>Infrastructure As Terraform Code</b>"
bg_image = "images/banner.jpg"
placeholder = "Dig into our open infra guides..."

# call to action
[Languages.en.params.cta]
enable = true
title = "Not sure of your app infrastructure!"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"